name: mi_tienda
description: A new Flutter e-commerce project with MVVM and Clean Architecture.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Supabase
  supabase_flutter: ^2.9.0

  # Routing
  go_router: ^14.0.0 # Modern routing solution

  # Local Storage (for cart and onboarding status)
  shared_preferences: ^2.2.3

  # Geolocation and Maps
  geolocator: ^12.0.0 # For getting user location
  google_maps_flutter: ^2.6.1 # For displaying maps

  # Image Picker for Profile
  image_picker: ^1.1.2 # ADD THIS LINE

  # Notifications
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6

  # UI/Utility
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1 # If you decide to use network images
  flutter_spinkit: ^5.2.1 # For loading animations
  intl: ^0.19.0 # For currency formatting

  equatable: ^2.0.7 # For value equality
  dio: ^5.4.0 # For network requests
  dartz: ^0.10.1 # For functional programming
  shimmer: ^3.0.0 # Para efectos de skeleton loader

  # Connectivity
  connectivity_plus: ^6.0.0 # Asegúrate de usar la última versión estable

  # Email validator
  email_validator: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.5
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/onboarding/