name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_lints: ^5.0.0
  shared_preferences: ^2.2.0
  get_it: ^7.6.0
  flutter_riverpod: ^2.3.6
  supabase_flutter: ^1.10.25
  go_router: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flavors:
  admin:
    app:
      name: "App Admin"
    bundle:
      ios: com.example.app.admin
      android: com.example.app.admin
  client:
    app:
      name: "App Client"
    bundle:
      ios: com.example.app.client
      android: com.example.app.client
  delivery:
    app:
      name: "App Delivery"
    bundle:
      ios: com.example.app.delivery
      android: com.example.app.delivery